title: Willy The Kiddie
description: ctfs write-ups and proof of concepts.
author: willythekiddie
github: https://github.com/willythekiddie
about: Simple cybersecurity enthusiast.

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/willythekiddie"


share:
  twitter_username: willythekiddie

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Github
      url: https://github.com/willythekiddie
    - text: XML Feed
      url: /feed.xml

url: "https://willythekiddie.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
